export const HOSPITALS = [
  {
    id: 'lautech',
    name: 'LAUTECH Teaching Hospital',
    distanceKm: 2.1,
    status: 'Accepting patients',
    address: 'Ogbomoso, Oyo State',
    phone: '08012345678',
    clinicDays: 'Mon-Fri',
    hours: '8AM - 4PM',
    directionsNote: 'From Ogbomoso town centre, take Ilorin Road northward. Hospital is on your right after LAUTECH main gate.',
  },
  {
    id: 'baptist',
    name: 'Baptist Medical Centre',
    distanceKm: 3.8,
    status: 'Accepting patients',
    address: 'Ogbomoso, Oyo State',
    phone: '08023456789',
    clinicDays: 'Mon-Sat',
    hours: '8AM - 5PM',
    directionsNote: 'From Ogbomoso town centre, head toward Aduke Road. Hospital gate is on your left, opposite the main market.',
  },
  {
    id: 'bowen',
    name: 'Bowen University Hospital',
    distanceKm: 5.2,
    status: 'Accepting patients',
    address: 'Ogbomoso, Oyo State',
    phone: '08034567890',
    clinicDays: 'Mon-Fri',
    hours: '9AM - 4PM',
    directionsNote: 'From Ogbomoso town centre, take the Iwo Road bypass. Hospital entrance is signposted on the right.',
  },
];
